### ISSUE TITLE
Channel 5

### ISSUE THREAD

**Issue by kentanttw** [samleong123/mewatchsg#15]
Hi, now the playlist not able to play channel 5. Anyway to resolve this?

**Comment by samleong123** [comment]
The issue should be resolved after the latest [Actions](https://github.com/samleong123/mewatchsg/actions/runs/3745128917).
Please refresh/update your playlist.

**Comment by kentanttw** [comment]
Thanks.

**Comment by kentanttw** [comment]
Hi, Can I find out how to refresh/update the Channel 5 link?It is still not working.KenOn 21 Dec 2022, at 8:04 AM, Sam Sam ***@***.***> wrote:﻿
The issue should be resolved after the latest Actions.
Please refresh/update your playlist.

**Comment by samleong123** [comment]
On my side its already working on Tivimate 
If u r using Tivimate try go to settings - playlist - update playlist and try again

or not

delete the playlist and reimport agian

**Comment by kentanttw** [comment]
It's ok now.

**Comment by kentanttw** [comment]
Hi,Thanks for the prompt update.It is working now after I removed and reimport the playlist.KenOn 21 Dec 2022, at 1:26 PM, Sam Sam ***@***.***> wrote:﻿
On my side its already working on Tivimate
If u r using Tivimate try go to settings - playlist - update playlist and try again
or not
delete the playlist and reimport agian
